### ISSUE TITLE
Getting the status of the invoice - YalaPay

### ISSUE THREAD

**Issue by noor-nn1802752** [cmps350s22/cmps350-content#8]
Dear Dr. Abdelkarim,

In U7 we are asked to show invoices based on the date range and the status of the invoice. If we wanted to use the JSON file as a test case, how do we retrieve the status of the invoice when in the JSON file there are no fields to indicate the status of the invoice?

**Comment by hani-hj1908619** [comment]
Invoice status is based on the balance amount as `invoice.amount - (sum of all payments for this invoice)`. If balance is 0 then it's paid, if balance=amount then its pending and otherwise partially paid.
